name: Arandu
options:
  bundleIdPrefix: com.devitools
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15"
  createIntermediateGroups: true

packages:
  cmark-gfm:
    url: https://github.com/KristopherGBaker/libcmark_gfm
    exactVersion: 0.29.4

targets:
  Arandu:
    type: application
    platform: macOS
    sources:
      - Sources/Arandu
    resources:
      - Sources/Arandu/Resources
    dependencies:
      - package: cmark-gfm
        product: libcmark_gfm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.devitools.arandu
        PRODUCT_NAME: Arandu
        INFOPLIST_FILE: Sources/Arandu/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: NO
        SWIFT_OBJC_BRIDGING_HEADER: ""
      configs:
        Debug:
          BUNDLE_VERSION: dev
        Release:
          BUNDLE_VERSION: 0.2.0
